2024-01-23 11:44:58,482 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:44:58,482 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:45:09,329 - ERROR - Exception while requesting URL: https://m.facebook.com/zuck
Exception: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /zuck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000172133C9310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"))
Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000172133C9310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /zuck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000172133C9310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\facebook_scraper\facebook_scraper.py", line 871, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\PC\PycharmProjects\FirstMission\venv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /zuck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000172133C9310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2024-01-23 11:45:09,342 - ERROR - An error occurred: HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /zuck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000172133C9310>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2024-01-23 11:45:09,342 - ERROR - An error occurred: local variable 'data' referenced before assignment
2024-01-23 11:45:09,342 - ERROR - An error occurred: local variable 'dataFromFacebook' referenced before assignment
2024-01-23 11:45:27,282 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:45:27,282 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:49:15,762 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:49:15,763 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 11:50:19,475 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:50:19,475 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:50:44,645 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:50:44,645 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 11:51:04,417 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:51:04,417 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:51:23,211 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:51:23,211 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:56:37,117 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:57:32,303 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:57:32,303 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 11:58:02,955 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:58:11,773 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:58:11,774 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 11:58:25,883 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:58:25,883 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 11:58:35,954 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:58:49,551 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 11:58:49,553 - ERROR - An error occurred: 'str' object has no attribute 'get'
2024-01-23 12:07:48,240 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:07:48,241 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 12:07:48,456 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:08:26,175 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:08:40,647 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:08:42,538 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:08:42,538 - ERROR - An error occurred: can only concatenate str (not "NoneType") to str
2024-01-23 12:13:32,366 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:32,367 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:32,367 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:32,797 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
2024-01-23 12:13:33,462 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:33,463 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:33,463 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:34,038 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
2024-01-23 12:13:39,799 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:39,799 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:39,799 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:40,127 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
2024-01-23 12:13:42,735 - ERROR - An error occurred: nonnumeric port: '//www.aisraeli.co.il/'
2024-01-23 12:13:45,874 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:45,874 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:45,874 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:46,196 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
2024-01-23 12:13:51,946 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:51,946 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:51,946 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:52,253 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
2024-01-23 12:13:58,188 - ERROR - Unable to extract top_post <class 'AssertionError'>:
2024-01-23 12:13:58,188 - ERROR - Friend_count extraction failed: list index out of range
2024-01-23 12:13:58,188 - ERROR - Follower_count extraction failed: 'NoneType' object has no attribute 'text'
2024-01-23 12:13:58,700 - ERROR - Following_count extraction failed: A login (cookies) is required to see this page
